# 生成 PCB 钻孔测试样例 DXF（多孔径，标准分行组码格式）
# 版图：100 × 80 mm，模拟真实 PCB 钻孔分布：
#   MOUNT Ø3.20  4  个安装孔（四角）
#   PWR   Ø1.50  4  个电源座插孔
#   CONN  Ø1.00  40 个 2×20 排针插孔（2.54 间距）
#   IC    Ø0.80  96 个 6×DIP-16 芯片插孔（2.54 间距，行距 7.62）
#   PTH   Ø0.60  60 个直插电阻孔（垂直安装，孔距 7.62）
#   VIA   Ø0.30  ~460 个缝合过孔（带抖动网格，避开器件区）
# 用法：powershell -File gen-drill-sample.ps1 [输出路径]

param([string]$OutPath = "$PSScriptRoot\..\src\GalvoStage.App\Samples\pcb-drill-multi.dxf")

$sb = [System.Text.StringBuilder]::new()
$script:holes = 0

function Add-Hole([double]$x, [double]$y, [double]$dia, [string]$layer) {
    $r = $dia / 2.0
    [void]$sb.AppendLine("0")
    [void]$sb.AppendLine("CIRCLE")
    [void]$sb.AppendLine("8")
    [void]$sb.AppendLine($layer)
    [void]$sb.AppendLine("10")
    [void]$sb.AppendLine($x.ToString("F4", [System.Globalization.CultureInfo]::InvariantCulture))
    [void]$sb.AppendLine("20")
    [void]$sb.AppendLine($y.ToString("F4", [System.Globalization.CultureInfo]::InvariantCulture))
    [void]$sb.AppendLine("40")
    [void]$sb.AppendLine($r.ToString("F4", [System.Globalization.CultureInfo]::InvariantCulture))
    $script:holes++
}

# --- DXF 头 ---
[void]$sb.AppendLine("999")
[void]$sb.AppendLine("PCB drill test sample - 6 diameters, generated by gen-drill-sample.ps1")
[void]$sb.AppendLine("0")
[void]$sb.AppendLine("SECTION")
[void]$sb.AppendLine("2")
[void]$sb.AppendLine("ENTITIES")

# 1) MOUNT：四角安装孔 Ø3.2
foreach ($p in @(@(5,5), @(95,5), @(5,75), @(95,75))) {
    Add-Hole $p[0] $p[1] 3.2 "MOUNT"
}

# 2) PWR：电源座插孔 Ø1.5（右下角）
foreach ($p in @(@(88,12), @(88,18), @(92,12), @(92,18))) {
    Add-Hole $p[0] $p[1] 1.5 "PWR"
}

# 3) CONN：2×20 排针 Ø1.0（底部，2.54 间距）
for ($c = 0; $c -lt 20; $c++) {
    $x = 12.0 + $c * 2.54
    Add-Hole $x  8.00 1.0 "CONN"
    Add-Hole $x 10.54 1.0 "CONN"
}

# 4) IC：6 片 DIP-16 Ø0.8（2 行 × 8 脚，2.54 间距，行距 7.62）
foreach ($org in @(@(18,24), @(43,24), @(68,24), @(18,42), @(43,42), @(68,42))) {
    for ($pin = 0; $pin -lt 8; $pin++) {
        $x = $org[0] + $pin * 2.54
        Add-Hole $x  $org[1]          0.8 "IC"
        Add-Hole $x ($org[1] + 7.62)  0.8 "IC"
    }
}

# 5) PTH：30 只垂直安装电阻 Ø0.6（顶部两条带，孔距 7.62）
for ($k = 0; $k -lt 30; $k++) {
    $x = 8.0 + $k * 3.0
    Add-Hole $x 58.00 0.6 "PTH"
    Add-Hole $x 65.62 0.6 "PTH"
}

# 6) VIA：缝合过孔 Ø0.3，带抖动的 30×20 网格，避开器件占用区
$rnd = [System.Random]::new(42)   # 固定种子保证可重现
function In-Rect([double]$x, [double]$y, $r) {
    return ($x -ge $r[0]) -and ($x -le $r[2]) -and ($y -ge $r[1]) -and ($y -le $r[3])
}
# 器件禁布区：排针 / 6 片 IC / 电阻带 / 电源座 / 安装孔角
$keepOut = @(
    @(10, 6, 62.3, 12.5),                                          # CONN
    @(16, 22, 39, 34), @(41, 22, 64, 34), @(66, 22, 89, 34),        # IC 第一排
    @(16, 40, 39, 52), @(41, 40, 64, 52), @(66, 40, 89, 52),        # IC 第二排
    @(6, 56, 98, 68),                                               # PTH 电阻带
    @(85, 9, 95, 21),                                               # PWR
    @(2, 2, 9, 9), @(91, 2, 98, 9), @(2, 71, 9, 78), @(91, 71, 98, 78)  # MOUNT
)
for ($gy = 0; $gy -lt 20; $gy++) {
    for ($gx = 0; $gx -lt 30; $gx++) {
        $x = 4.0 + $gx * (92.0 / 29.0) + ($rnd.NextDouble() - 0.5) * 0.8
        $y = 4.0 + $gy * (72.0 / 19.0) + ($rnd.NextDouble() - 0.5) * 0.8
        $blocked = $false
        foreach ($r in $keepOut) { if (In-Rect $x $y $r) { $blocked = $true; break } }
        if (-not $blocked) { Add-Hole $x $y 0.3 "VIA" }
    }
}

# --- DXF 尾 ---
[void]$sb.AppendLine("0")
[void]$sb.AppendLine("ENDSEC")
[void]$sb.AppendLine("0")
[void]$sb.AppendLine("EOF")

$OutPath = [System.IO.Path]::GetFullPath($OutPath)
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Generated $($OutPath): $($script:holes) holes"
