# 生成含"特大孔"的 PCB 钻孔测试样例 DXF（多孔径，标准分行组码格式）
# 版图：300 × 200 mm，除常规多孔径外，额外包含半径 20mm（Ø40）的特大孔，
# 用于验证超幅面孔加工能力与 docs/06 §7.4 逐孔动力学预检（r ≫ 半视场）。
#   BIGHOLE Ø40.00  3  个特大孔（半径 20mm，超振镜幅面，由平台承载）
#   MOUNT   Ø3.20   4  个安装孔（四角）
#   PWR     Ø2.00   4  个电源座插孔
#   CONN    Ø1.00   40 个 2×20 排针插孔（2.54 间距）
#   IC      Ø0.80   64 个 4×DIP-16 芯片插孔（2.54 间距，行距 7.62）
#   PTH     Ø0.60   40 个直插电阻孔（孔距）
#   VIA     Ø0.30   缝合过孔（带抖动网格，避开器件区与特大孔）
# 用法：powershell -File gen-drill-bighole-sample.ps1 [输出路径]

param([string]$OutPath = "$PSScriptRoot\..\src\GalvoStage.App\Samples\pcb-drill-bighole.dxf")

$sb = [System.Text.StringBuilder]::new()
$script:holes = 0

function Add-Hole([double]$x, [double]$y, [double]$dia, [string]$layer) {
    $r = $dia / 2.0
    [void]$sb.AppendLine("0")
    [void]$sb.AppendLine("CIRCLE")
    [void]$sb.AppendLine("8")
    [void]$sb.AppendLine($layer)
    [void]$sb.AppendLine("10")
    [void]$sb.AppendLine($x.ToString("F4", [System.Globalization.CultureInfo]::InvariantCulture))
    [void]$sb.AppendLine("20")
    [void]$sb.AppendLine($y.ToString("F4", [System.Globalization.CultureInfo]::InvariantCulture))
    [void]$sb.AppendLine("40")
    [void]$sb.AppendLine($r.ToString("F4", [System.Globalization.CultureInfo]::InvariantCulture))
    $script:holes++
}

# --- DXF 头 ---
[void]$sb.AppendLine("999")
[void]$sb.AppendLine("PCB drill sample with oversized holes (r=20mm) - generated by gen-drill-bighole-sample.ps1")
[void]$sb.AppendLine("0")
[void]$sb.AppendLine("SECTION")
[void]$sb.AppendLine("2")
[void]$sb.AppendLine("ENTITIES")

# 0) BIGHOLE：特大孔 Ø40（半径 20mm），横排居中，中心间距 90mm（孔间净距 50mm）
$bigHoleCenters = @(@(60, 155), @(150, 155), @(240, 155))
foreach ($p in $bigHoleCenters) {
    Add-Hole $p[0] $p[1] 40.0 "BIGHOLE"
}

# 1) MOUNT：四角安装孔 Ø3.2
foreach ($p in @(@(10,10), @(290,10), @(10,190), @(290,190))) {
    Add-Hole $p[0] $p[1] 3.2 "MOUNT"
}

# 2) PWR：电源座插孔 Ø2.0（右下角）
foreach ($p in @(@(268,20), @(268,26), @(274,20), @(274,26))) {
    Add-Hole $p[0] $p[1] 2.0 "PWR"
}

# 3) CONN：2×20 排针 Ø1.0（底部，2.54 间距）
for ($c = 0; $c -lt 20; $c++) {
    $x = 20.0 + $c * 2.54
    Add-Hole $x  15.00 1.0 "CONN"
    Add-Hole $x 17.54 1.0 "CONN"
}

# 4) IC：4 片 DIP-16 Ø0.8（2 行 × 8 脚，2.54 间距，行距 7.62）
foreach ($org in @(@(90,15), @(140,15), @(90,33), @(140,33))) {
    for ($pin = 0; $pin -lt 8; $pin++) {
        $x = $org[0] + $pin * 2.54
        Add-Hole $x  $org[1]          0.8 "IC"
        Add-Hole $x ($org[1] + 7.62)  0.8 "IC"
    }
}

# 5) PTH：20 只垂直安装电阻 Ø0.6（两条带，孔距 3.0）
for ($k = 0; $k -lt 20; $k++) {
    $x = 20.0 + $k * 3.0
    Add-Hole $x 55.00 0.6 "PTH"
    Add-Hole $x 62.62 0.6 "PTH"
}

# 6) VIA：缝合过孔 Ø0.3，带抖动的 40×16 网格，避开器件占用区与特大孔
$rnd = [System.Random]::new(42)   # 固定种子保证可重现
function In-Rect([double]$x, [double]$y, $r) {
    return ($x -ge $r[0]) -and ($x -le $r[2]) -and ($y -ge $r[1]) -and ($y -le $r[3])
}
# 器件禁布矩形区
$keepOut = @(
    @(16, 13, 70, 20),                                             # CONN
    @(88, 13, 110, 25), @(138, 13, 160, 25),                        # IC 第一排
    @(88, 31, 110, 43), @(138, 31, 160, 43),                        # IC 第二排
    @(16, 53, 84, 65),                                             # PTH 电阻带
    @(264, 16, 278, 30),                                           # PWR
    @(4, 4, 16, 16), @(284, 4, 296, 16), @(4, 184, 16, 196), @(284, 184, 296, 196)  # MOUNT 角
)
# 特大孔禁布：中心 ± (半径 + 3mm 安全边)
$bigKeepR = 23.0
for ($gy = 0; $gy -lt 16; $gy++) {
    for ($gx = 0; $gx -lt 40; $gx++) {
        $x = 6.0 + $gx * (288.0 / 39.0) + ($rnd.NextDouble() - 0.5) * 0.8
        $y = 6.0 + $gy * (188.0 / 15.0) + ($rnd.NextDouble() - 0.5) * 0.8
        $blocked = $false
        foreach ($r in $keepOut) { if (In-Rect $x $y $r) { $blocked = $true; break } }
        if (-not $blocked) {
            foreach ($c in $bigHoleCenters) {
                $dx = $x - $c[0]; $dy = $y - $c[1]
                if (($dx * $dx + $dy * $dy) -le ($bigKeepR * $bigKeepR)) { $blocked = $true; break }
            }
        }
        if (-not $blocked) { Add-Hole $x $y 0.3 "VIA" }
    }
}

# --- DXF 尾 ---
[void]$sb.AppendLine("0")
[void]$sb.AppendLine("ENDSEC")
[void]$sb.AppendLine("0")
[void]$sb.AppendLine("EOF")

$OutPath = [System.IO.Path]::GetFullPath($OutPath)
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Generated $($OutPath): $($script:holes) holes"
